# Generated by Django 3.2.5 on 2021-07-27 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milestone4', '0002_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='join_date',
            field=models.DateField(default=''),
        ),
    ]
