# Generated by Django 3.2.5 on 2021-07-27 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milestone4', '0003_alter_user_join_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='2021-01-01', max_length=75),
        ),
    ]
