# Generated by Django 3.2.5 on 2021-07-27 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milestone4', '0004_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='join_date',
            field=models.DateField(default='2021-01-01'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='', max_length=75),
        ),
    ]
