# Generated by Django 3.2.5 on 2021-07-27 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milestone4', '0005_auto_20210727_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=5.0, max_digits=2),
        ),
        migrations.AlterField(
            model_name='seller',
            name='sales',
            field=models.IntegerField(default=0),
        ),
    ]
